# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"to_np": "00_utils.ipynb",
         "zero_grad": "00_utils.ipynb",
         "float64": "00_utils.ipynb",
         "compare_fwd_bwd": "00_utils.ipynb",
         "timed": "00_utils.ipynb",
         "benchmark_fwd_bwd": "00_utils.ipynb",
         "report": "00_utils.ipynb",
         "load_cupy_module": "00_utils.ipynb"}

modules = ["utils.py"]

doc_url = "https://davidcpage.github.io/mctc/"

git_url = "https://github.com/davidcpage/mctc/tree/master/"

def custom_doc_links(name): return None
