# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"to_np": "00_utils.ipynb",
         "zero_grad": "00_utils.ipynb",
         "float64": "00_utils.ipynb",
         "compare_fwd_bwd": "00_utils.ipynb",
         "timed": "00_utils.ipynb",
         "benchmark_fwd_bwd": "00_utils.ipynb",
         "report": "00_utils.ipynb",
         "load_cupy_func": "00_utils.ipynb",
         "load_cupy_module": "00_utils.ipynb",
         "device": "05_Sparse.ipynb",
         "generate_sample_inputs": "03_CTC_loss_simple.ipynb",
         "loss_pytorch": "01_CTC_loss.ipynb",
         "interleave_blanks": "01_CTC_loss.ipynb",
         "prepare_inputs": "02_CTC_loss_banded.ipynb",
         "loss_basic": "02_CTC_loss_banded.ipynb",
         "semiring": "01_CTC_loss.ipynb",
         "neginf": "01_CTC_loss.ipynb",
         "Log": "01_CTC_loss.ipynb",
         "fwd_bwd": "02_CTC_loss_banded.ipynb",
         "masked_grad": "01_CTC_loss.ipynb",
         "loss_py": "02_CTC_loss_banded.ipynb",
         "loss_cupy": "02_CTC_loss_banded.ipynb",
         "cupy_funcs": "05_Sparse.ipynb",
         "max_grad": "01_CTC_loss.ipynb",
         "Max": "01_CTC_loss.ipynb",
         "viterbi_alignments": "02_CTC_loss_banded.ipynb",
         "soft_alignments": "02_CTC_loss_banded.ipynb",
         "loss_direct_cupy": "01_CTC_loss.ipynb",
         "Prob": "01_CTC_loss.ipynb",
         "window_start_positions": "02_CTC_loss_banded.ipynb",
         "loss_masked": "02_CTC_loss_banded.ipynb",
         "logZ_fwd": "03_CTC_loss_simple.ipynb",
         "dot": "03_CTC_loss_simple.ipynb",
         "LogZ": "04_Normalisation.ipynb",
         "logZ_py": "04_Normalisation.ipynb",
         "mean": "03_CTC_loss_simple.ipynb",
         "logZ_cupy": "03_CTC_loss_simple.ipynb",
         "generate_test_example": "04_Normalisation.ipynb",
         "fused_batch_Mv": "04_Normalisation.ipynb",
         "LogZViterbi": "04_Normalisation.ipynb",
         "logz": "04_Normalisation.ipynb",
         "Mv_scan_py": "05_Sparse.ipynb",
         "transpose": "05_Sparse.ipynb",
         "logZ_scan_py": "05_Sparse.ipynb",
         "ctc_loss_scan_py": "05_Sparse.ipynb",
         "Mv_scan_cupy": "05_Sparse.ipynb",
         "logZ_scan": "05_Sparse.ipynb",
         "ctc_loss_scan": "05_Sparse.ipynb",
         "cupy_func": "05_Sparse.ipynb",
         "logZ": "05_Sparse.ipynb",
         "ctc_loss": "05_Sparse.ipynb"}

modules = ["utils.py",
           "ctc.py",
           "ctc_banded.py",
           "ctc_simple.py",
           "normalisation.py",
           "sparse.py"]

doc_url = "https://davidcpage.github.io/mctc/"

git_url = "https://github.com/davidcpage/mctc/tree/master/"

def custom_doc_links(name): return None
