# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"to_np": "00_utils.ipynb",
         "zero_grad": "00_utils.ipynb",
         "float64": "00_utils.ipynb",
         "compare_fwd_bwd": "00_utils.ipynb",
         "timed": "00_utils.ipynb",
         "benchmark_fwd_bwd": "00_utils.ipynb",
         "report": "00_utils.ipynb",
         "load_cupy_func": "00_utils.ipynb",
         "load_cupy_module": "00_utils.ipynb",
         "device": "01_CTC_loss.ipynb",
         "generate_example_inputs": "01_CTC_loss.ipynb",
         "ctc_loss_pytorch": "01_CTC_loss.ipynb",
         "interleave_blanks": "01_CTC_loss.ipynb",
         "prepare_inputs": "01_CTC_loss.ipynb",
         "ctc_logz_fwd": "01_CTC_loss.ipynb",
         "ctc_loss_basic": "01_CTC_loss.ipynb",
         "semiring": "01_CTC_loss.ipynb",
         "neginf": "01_CTC_loss.ipynb",
         "Log": "01_CTC_loss.ipynb",
         "ctc_fwd_bwd": "01_CTC_loss.ipynb",
         "masked_grad": "01_CTC_loss.ipynb",
         "ctc_loss_py": "01_CTC_loss.ipynb",
         "ctc_loss_cupy": "01_CTC_loss.ipynb",
         "cupy_funcs": "01_CTC_loss.ipynb",
         "max_grad": "01_CTC_loss.ipynb",
         "Max": "01_CTC_loss.ipynb",
         "viterbi_alignments": "01_CTC_loss.ipynb",
         "soft_alignments": "01_CTC_loss.ipynb",
         "ctc_loss_direct_cupy": "01_CTC_loss.ipynb",
         "Prob": "01_CTC_loss.ipynb"}

modules = ["utils.py",
           "ctc.py"]

doc_url = "https://davidcpage.github.io/mctc/"

git_url = "https://github.com/davidcpage/mctc/tree/master/"

def custom_doc_links(name): return None
